# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yilqQZL_GdN7UpUMPR_KWs6McFeZyxE
"""

scores = input().split()

count = 0

for s in scores:
    if int(s) < 60:
        count += 1

print(count)